name: vipfall2020
dependencies:
  - freetype=2.8
  - libpng=1.6.34
  - matplotlib=2.2.2
  - mkl=2018.0.3=1
  - numpy=1.14.3
  - openssl=1.0.2o
  - pandas=0.23.0
  - seaborn=0.10.1
  - pip=10.0.1=py36_0
  - pyqt=5.9.2
  - python=3.6.5
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.4=py36_0
  - qt=5.9.5
  - scikit-learn=0.20
  - scipy=1.1.0
  - sqlite=3.23.1
  - zlib=1.2.11
  - pip:
    - datetime
